name: Deploy to AWS EC2 on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Environment
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kanwargrewal/lululemon_api:latest

      - name: Copy Docker Compose to AWS EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
          scp -i ~/.ssh/id_rsa docker-compose.yml ubuntu@$SERVER_IP:/home/ubuntu/

      - name: Deploy Container on AWS EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@$SERVER_IP << 'EOF'
            # Ensure Docker is installed
            if ! command -v docker &> /dev/null
            then
                echo "Installing Docker..."
                sudo apt update
                sudo apt install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
            fi

            # Ensure Docker Compose is installed
            if ! command -v docker-compose &> /dev/null
            then
                echo "Installing Docker Compose..."
                sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            fi

            echo "Pulling Docker image..."
            docker pull kanwargrewal/lululemon_api:latest
            echo "Running Docker Compose..."
            docker-compose -f /home/ubuntu/docker-compose.yml up -d

            echo "Checking database permissions..."
            sudo chown ubuntu:ubuntu /home/ubuntu/lululemon_api/db.sqlite3
            sudo chmod 664 /home/ubuntu/lululemon_api/db.sqlite3
          EOF
